# baseURL = 'https://willf.github.io/ai-for-ancient-languages/'
languageCode = 'en-us'
title = 'AI For Ancient Languages'
theme = 'ananke'
author = 'Will Fitzgerald'
description = 'AI For Ancient Languages'
copyright = 'Will Fitzgerald'
[params]
body_classes = "georgia bg-near-white"
[caches]
[caches.images]
dir = ':cacheDir/images'
